require:
  - rubocop-capybara
  - rubocop-rails

AllCops:
  NewCops: enable
  Includes:
    - Rakefile
    - config.ru
    - app/**/*
  Excludes:
    - db/**
    - config/**
    - script/**
    - vendor/**/* # Circle adds the rubies here
    - bin/**

Documentation:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Layout/LineLength:
  Max: 120
